(()=>{
const API_BASE=window.BITEY_API_BASE||'https://bitey-ia-suprabrain.onrender.com';
const KEY='bitey_web_conversations_v2';
const $=s=>document.querySelector(s);
const messages=$('#messages'),form=$('#chat-form'),input=$('#prompt'),send=$('#send'),activity=$('#activity'),activityText=$('#activity-text'),activityElapsed=$('#activity-elapsed'),eventsBox=$('#activity-events'),history=$('#history');
const state={conversationId:null,title:'Nueva conversación',mode:'auto',busy:false,abortController:null,lastPrompt:'',lastAnswer:'',lastAnswerExtra:null,activityStartedAt:0,activityTimer:null,activityStageTimer:null,activityStage:0};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const createRequestId=()=>{try{if(window.crypto?.randomUUID)return window.crypto.randomUUID()}catch(_){}return 'req-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10)};
const clean=v=>String(v??'').replace(/<think>[\s\S]*?<\/think>/gi,'').replace(/<analysis>[\s\S]*?<\/analysis>/gi,'').replace(/<reasoning>[\s\S]*?<\/reasoning>/gi,'').trim();
const renderText=v=>{const source=clean(v);const parts=source.split(/\`\`\`([\s\S]*?)\`\`\`/g);return parts.map((part,i)=>i%2===1?'<pre class="bitey-code"><code>'+esc(part.trim())+'</code></pre>':esc(part).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>')).join('')};
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const save=()=>{if(!state.conversationId)return;const a=load().filter(x=>x.id!==state.conversationId);a.unshift({id:state.conversationId,title:state.title,updatedAt:Date.now()});localStorage.setItem(KEY,JSON.stringify(a.slice(0,100)));renderHistory()};
function renderHistory(){if(!history)return;history.innerHTML='';for(const x of load()){const b=document.createElement('button');b.className='history-item'+(x.id===state.conversationId?' active':'');b.textContent=x.title||'Conversación';b.onclick=()=>openConversation(x.id);history.appendChild(b)}if(!history.children.length){const e=document.createElement('div');e.className='history-empty';e.textContent='Tus conversaciones aparecerán aquí.';history.appendChild(e)}}
const sendIcon='<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="m5 12 14-7-3 14-4-6-7-1Z"/><path d="m12 13 7-8"/></svg>';const stopIcon='<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><rect x="7" y="7" width="10" height="10" rx="2"/></svg>';function setActivity(on,label){if(activity){activity.hidden=!on;if(on){activityText.textContent=label||'Bitey está procesando tu solicitud…';state.activityStartedAt=Date.now();state.activityStage=0;if(state.activityTimer)clearInterval(state.activityTimer);if(state.activityStageTimer)clearInterval(state.activityStageTimer);state.activityTimer=setInterval(()=>{if(activityElapsed)activityElapsed.textContent=((Date.now()-state.activityStartedAt)/1000).toFixed(1).replace('.',',')+' s'},100)}}if(!on&&state.activityTimer){clearInterval(state.activityTimer);state.activityTimer=null}if(!on&&state.activityStageTimer){clearInterval(state.activityStageTimer);state.activityStageTimer=null}if(send){send.disabled=false;send.innerHTML=on?stopIcon:sendIcon;send.setAttribute('aria-label',on?'Detener generación':'Enviar mensaje');send.title=on?'Detener generación':'Enviar mensaje'}}
function showEvents(items){if(!eventsBox)return;eventsBox.innerHTML='';const seen=new Set();const list=(items||[]).map(x=>String(x||'').replace(/\\s+/g,' ').trim()).filter(Boolean).filter(item=>{const key=item.toLocaleLowerCase();if(seen.has(key))return false;seen.add(key);return true}).slice(0,8);for(const item of list){const d=document.createElement('div');d.className='activity-event';d.innerHTML='<span class="activity-event-dot"></span><span>'+esc(item)+'</span>';eventsBox.appendChild(d)}eventsBox.hidden=!list.length;eventsBox.setAttribute('aria-hidden',String(!list.length))}
function renderValidation(extra){
  if(!extra?.answer_validation)return '';
  const v=extra.answer_validation;
  const contradictions=Number(extra?.evidence_analysis?.contradiction_count||0);
  if(v.valid&&!contradictions)return '<div class="answer-validation"><span class="answer-validation-dot"></span><span>Respuesta verificada</span></div>';
  if(contradictions)return '<div class="answer-validation warning"><span class="answer-validation-dot"></span><span>Se detectaron '+contradictions+' posible'+(contradictions===1?' conflicto':'s conflictos')+' entre fuentes</span></div>';
  return '<div class="answer-validation warning"><span class="answer-validation-dot"></span><span>Respuesta entregada con incertidumbre</span></div>';
}
function addMessage(role,text,extra,meta={}){const row=document.createElement('article');row.className='message '+role;if(meta.prompt)row.dataset.prompt=String(meta.prompt);const body=document.createElement('div');body.className='message-content';body.innerHTML=role==='assistant'?renderText(clean(text)):esc(text).replace(/\n/g,'<br>');row.appendChild(body);if(role==='assistant'&&extra){state.lastAnswer=String(text||'');state.lastAnswerExtra=extra;const validation=renderValidation(extra);if(validation){const box=document.createElement('div');box.className='answer-validation-wrap';box.innerHTML=validation;row.appendChild(box)}}if(role==='assistant'&&text){const actions=document.createElement('div');actions.className='answer-actions';const copy=document.createElement('button');copy.type='button';copy.className='answer-action';copy.textContent='Copiar';copy.title='Copiar respuesta';copy.onclick=async()=>{try{await navigator.clipboard.writeText(String(text||''));copy.textContent='Copiado';setTimeout(()=>copy.textContent='Copiar',1200)}catch(_){copy.textContent='No disponible'}};actions.appendChild(copy);const regen=document.createElement('button');regen.type='button';regen.className='answer-action';regen.textContent='Regenerar';regen.title='Regenerar esta respuesta';regen.onclick=()=>{const prompt=row.dataset.prompt||'';if(!state.busy&&prompt)regenerateMessage(row,prompt)};actions.appendChild(regen);row.appendChild(actions)}if(extra&&Array.isArray(extra.sources)&&extra.sources.length){const seen=new Set();const sources=extra.sources.filter(s=>s&&s.url).filter(s=>{const key=String(s.url).trim().toLowerCase();if(seen.has(key))return false;seen.add(key);return true}).slice(0,8);if(sources.length){const box=document.createElement('div');box.className='bitey-sources';const title=document.createElement('div');title.className='bitey-sources-title';title.textContent=sources.length===1?'Fuente verificada':'Fuentes verificadas';box.appendChild(title);sources.forEach((s,i)=>{const a=document.createElement('a');a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='[S'+(i+1)+'] '+(s.title||s.url);box.appendChild(a)});row.appendChild(box)}}messages.appendChild(row);row.scrollIntoView({behavior:'smooth',block:'end'})}
function reset(){state.conversationId=null;state.title='Nueva conversación';messages.innerHTML='<div class="welcome"><img class="bitey-logo" src="./bitey-logo.svg" alt="Bitey IA"/><div class="eyebrow">Bitey IA</div><h1>Hola, soy Bitey.</h1><p class="hero-copy">¿En qué estás pensando?</p><div class="starter-row"><button data-starter="Investiga este tema y explícamelo">Investigar</button><button data-starter="Ayúdame a crear una solución">Crear</button><button data-starter="Ayúdame a analizar esta idea">Analizar</button></div></div>';bindStarters();renderHistory();input?.focus()}
async function openConversation(id){try{const r=await fetch(API_BASE+'/api/v1/conversations/'+encodeURIComponent(id)+'/messages');if(!r.ok)throw Error('history_'+r.status);const d=await r.json();state.conversationId=id;const item=load().find(x=>x.id===id);state.title=item?.title||'Conversación';messages.innerHTML='';for(const m of d.messages||[])if(m.role==='user'||m.role==='assistant')addMessage(m.role,m.content,{});renderHistory()}catch(e){console.error(e)}}
async function sendMessage(raw,options={}){const text=String(raw||'').trim();if(!text)return;if(state.busy){state.abortController?.abort();return}state.busy=true;state.lastPrompt=text;state.abortController=new AbortController();const requestId=createRequestId();setActivity(true,options.regenerate?'Bitey IA está regenerando la respuesta…':'Bitey IA está procesando tu solicitud…');showEvents([]);if(messages.querySelector('.welcome'))messages.innerHTML='';if(!options.regenerate)addMessage('user',text,{},{});input.value='';input.style.height='auto';if(state.title==='Nueva conversación')state.title=text.slice(0,60);try{const r=await fetch(API_BASE+'/api/v2/chat',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({conversation_id:state.conversationId,message:text,mode:state.mode,metadata:{channel:'web',interface:'bitey-web-v2',request_id:requestId,regenerate:Boolean(options.regenerate)}}),signal:state.abortController.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||d.error||('HTTP '+r.status));state.conversationId=d.conversation_id;const answerExtra={sources:d.sources,answer_validation:d.answer_validation,evidence_analysis:d.evidence_analysis};addMessage('assistant',clean(d.answer)||'No recibí una respuesta pública válida.',answerExtra,{prompt:text});showEvents(d.activity_events||[]);if(activityText)activityText.textContent='Bitey IA preparó la respuesta';save()}catch(e){if(e?.name==='AbortError'){showEvents(['Generación detenida por el usuario.']);addMessage('assistant','Generación detenida. Puedes volver a intentarlo.',{})}else{addMessage('assistant','No pude completar la solicitud en este momento. La conversación se conserva para reintentar.',{});showEvents([String(e.message||e)])}}finally{state.busy=false;state.abortController=null;setActivity(false);input?.focus()}}
function regenerateMessage(row,prompt){if(!row||!prompt||state.busy)return;row.remove();sendMessage(prompt,{regenerate:true})}
function bindStarters(){document.querySelectorAll('[data-starter]').forEach(b=>b.onclick=()=>{input.value=b.dataset.starter;form.requestSubmit()})}
function installModeSelector(){if(!input||$('#bitey-mode'))return;const wrap=document.createElement('select');wrap.id='bitey-mode';wrap.title='Modo de Bitey IA';[['auto','Auto'],['chat','Chat'],['research','Investigación'],['math','Matemática'],['code','Código']].forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;wrap.appendChild(o)});wrap.onchange=()=>state.mode=wrap.value;wrap.className='bitey-mode';$('.composer')?.appendChild(wrap)}
if(form)form.onsubmit=e=>{e.preventDefault();sendMessage(input.value)};if($('#new-chat'))$('#new-chat').onclick=reset;if(input)input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}};input?.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,180)+'px'});installModeSelector();bindStarters();renderHistory();window.BiteyChatV2={sendMessage,reset,openConversation,retry:()=>state.lastPrompt?sendMessage(state.lastPrompt):null,regenerateMessage,stop:()=>state.abortController?.abort()};
})();