(()=>{
const API_BASE=window.BITEY_API_BASE||'https://bitey-ia-suprabrain.onrender.com';
const KEY='bitey_web_conversations_v2';
const $=s=>document.querySelector(s);
const messages=$('#messages'),form=$('#chat-form'),input=$('#prompt'),send=$('#send'),activity=$('#activity'),activityText=$('#activity-text'),activityElapsed=$('#activity-elapsed'),eventsBox=$('#activity-events'),history=$('#history');
const state={conversationId:null,title:'Nueva conversación',mode:'auto',busy:false,abortController:null,lastPrompt:'',activityStartedAt:0,activityTimer:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').replace(/<think>[\s\S]*?<\/think>/gi,'').replace(/<analysis>[\s\S]*?<\/analysis>/gi,'').replace(/<reasoning>[\s\S]*?<\/reasoning>/gi,'').trim();
const renderText=v=>{const source=clean(v);const parts=source.split(/\`\`\`([\s\S]*?)\`\`\`/g);return parts.map((part,i)=>i%2===1?'<pre class="bitey-code"><code>'+esc(part.trim())+'</code></pre>':esc(part).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>')).join('')};
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const save=()=>{if(!state.conversationId)return;const a=load().filter(x=>x.id!==state.conversationId);a.unshift({id:state.conversationId,title:state.title,updatedAt:Date.now()});localStorage.setItem(KEY,JSON.stringify(a.slice(0,100)));renderHistory()};
function renderHistory(){if(!history)return;history.innerHTML='';for(const x of load()){const b=document.createElement('button');b.className='history-item'+(x.id===state.conversationId?' active':'');b.textContent=x.title||'Conversación';b.onclick=()=>openConversation(x.id);history.appendChild(b)}if(!history.children.length){const e=document.createElement('div');e.className='history-empty';e.textContent='Tus conversaciones aparecerán aquí.';history.appendChild(e)}}
function setActivity(on,label){if(activity){activity.hidden=!on;if(on){activityText.textContent=label||'Bitey está trabajando…';state.activityStartedAt=Date.now();if(state.activityTimer)clearInterval(state.activityTimer);state.activityTimer=setInterval(()=>{if(activityElapsed)activityElapsed.textContent=((Date.now()-state.activityStartedAt)/1000).toFixed(1).replace('.',',')+' s'},100)}}if(!on&&state.activityTimer){clearInterval(state.activityTimer);state.activityTimer=null}if(send){send.disabled=false;send.textContent=on?'■':'➤';send.setAttribute('aria-label',on?'Detener generación':'Enviar mensaje');send.title=on?'Detener generación':'Enviar mensaje'}}
function showEvents(items){if(!eventsBox)return;eventsBox.innerHTML='';for(const item of items||[]){const d=document.createElement('div');d.className='activity-event';d.textContent=item;eventsBox.appendChild(d)}eventsBox.hidden=!(items&&items.length)}
function statusEvents(d){const out=[];const s=d?.evidence_status;if(s==='verified')out.push('Evidencia: verificada.');else if(s==='conflicting')out.push('Evidencia: fuentes con diferencias detectadas.');else if(s==='no_evidence')out.push('Evidencia: no se pudo verificar.');const e=d?.evaluation;if(e?.decision)out.push(`Control de calidad: ${e.decision}${typeof e.confidence==='number'?` · ${Math.round(e.confidence*100)}%`:''}.`);const p=d?.provider?.selected;if(p)out.push(`Modelo: ${p}.`);return out}
function addMessage(role,text,extra){const row=document.createElement('article');row.className='message '+role;const body=document.createElement('div');body.className='message-content';body.innerHTML=role==='assistant'?renderText(clean(text)):esc(text).replace(/\n/g,'<br>');row.appendChild(body);if(extra&&extra.sources&&extra.sources.length){const box=document.createElement('div');box.className='bitey-sources';const title=document.createElement('div');title.className='bitey-sources-title';title.textContent='Fuentes verificadas';box.appendChild(title);extra.sources.forEach((s,i)=>{const a=document.createElement('a');a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='[S'+(i+1)+'] '+(s.title||s.url);box.appendChild(a)});row.appendChild(box)}messages.appendChild(row);row.scrollIntoView({behavior:'smooth',block:'end'})}
function reset(){state.conversationId=null;state.title='Nueva conversación';messages.innerHTML='<div class="welcome"><img class="bitey-logo" src="./bitey-logo.svg" alt="Bitey IA"/><div class="eyebrow">Bitey IA</div><h1>Hola, soy Bitey.</h1><p class="hero-copy">¿En qué estás pensando?</p><div class="starter-row"><button data-starter="Investiga este tema y explícamelo">Investigar</button><button data-starter="Ayúdame a crear una solución">Crear</button><button data-starter="Ayúdame a analizar esta idea">Analizar</button></div></div>';bindStarters();renderHistory();input?.focus()}
async function openConversation(id){try{const r=await fetch(API_BASE+'/api/v1/conversations/'+encodeURIComponent(id)+'/messages');if(!r.ok)throw Error('history_'+r.status);const d=await r.json();state.conversationId=id;const item=load().find(x=>x.id===id);state.title=item?.title||'Conversación';messages.innerHTML='';for(const m of d.messages||[])if(m.role==='user'||m.role==='assistant')addMessage(m.role,m.content,{});renderHistory()}catch(e){console.error(e)}}
async function sendMessage(raw){const text=String(raw||'').trim();if(!text)return;if(state.busy){state.abortController?.abort();return}state.busy=true;state.lastPrompt=text;state.abortController=new AbortController();setActivity(true,'Bitey está analizando tu solicitud…');showEvents(['Analizando intención…']);if(messages.querySelector('.welcome'))messages.innerHTML='';addMessage('user',text,{});input.value='';input.style.height='auto';if(state.title==='Nueva conversación')state.title=text.slice(0,60);try{const r=await fetch(API_BASE+'/api/v2/chat',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({conversation_id:state.conversationId,message:text,mode:state.mode,metadata:{channel:'web',interface:'bitey-web-v2'}}),signal:state.abortController.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||d.error||('HTTP '+r.status));state.conversationId=d.conversation_id;addMessage('assistant',clean(d.answer)||'No recibí una respuesta pública válida.',{sources:d.sources});showEvents([...(d.activity_events||[]),...statusEvents(d)]);save()}catch(e){if(e?.name==='AbortError'){showEvents(['Generación detenida por el usuario.']);addMessage('assistant','Generación detenida. Puedes volver a intentarlo.',{})}else{addMessage('assistant','No pude completar la solicitud en este momento. La conversación se conserva para reintentar.',{});showEvents([String(e.message||e)])}}finally{state.busy=false;state.abortController=null;setActivity(false);input?.focus()}}
function bindStarters(){document.querySelectorAll('[data-starter]').forEach(b=>b.onclick=()=>{input.value=b.dataset.starter;form.requestSubmit()})}
function installModeSelector(){if(!input||$('#bitey-mode'))return;const wrap=document.createElement('select');wrap.id='bitey-mode';wrap.title='Modo de Bitey IA';[['auto','Auto'],['chat','Chat'],['research','Investigación'],['math','Matemática'],['code','Código']].forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;wrap.appendChild(o)});wrap.onchange=()=>state.mode=wrap.value;$('.composer-main')?.prepend(wrap)}
if(form)form.onsubmit=e=>{e.preventDefault();sendMessage(input.value)};if($('#new-chat'))$('#new-chat').onclick=reset;if(input)input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}};input?.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,180)+'px'});installModeSelector();bindStarters();renderHistory();window.BiteyChatV2={sendMessage,reset,openConversation,retry:()=>state.lastPrompt?sendMessage(state.lastPrompt):null,stop:()=>state.abortController?.abort()};
})();