(()=>{
const API_BASE=window.BITEY_API_BASE||'https://bitey-ia-suprabrain.onrender.com';
const KEY='bitey_web_conversations_v2';
const $=s=>document.querySelector(s);
const messages=$('#messages'),form=$('#chat-form'),input=$('#prompt'),send=$('#send'),activity=$('#activity'),activityText=$('#activity-text'),activityElapsed=$('#activity-elapsed'),eventsBox=$('#activity-events'),history=$('#history');
const state={conversationId:null,title:'Nueva conversación',mode:'auto',busy:false,abortController:null,lastPrompt:'',lastAnswer:'',lastAnswerExtra:null,activityStartedAt:0,activityTimer:null,activityStageTimer:null,activityPollTimer:null,activityStage:0};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const createRequestId=()=>{try{if(window.crypto?.randomUUID)return window.crypto.randomUUID()}catch(_){}return 'req-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10)};
const clean=v=>String(v??'').replace(/<think>[\s\S]*?<\/think>/gi,'').replace(/<analysis>[\s\S]*?<\/analysis>/gi,'').replace(/<reasoning>[\s\S]*?<\/reasoning>/gi,'').trim();
const renderText=v=>{const source=clean(v);const parts=source.split(/\\x60\\x60\\x60([\\s\\S]*?)\\x60\\x60\\x60/g);return parts.map((part,i)=>{if(i%2===1)return '<pre class="bitey-code"><code>'+esc(part.trim())+'</code></pre>';let s=esc(part);s=s.replace(/\\[([^\\]]+)\\]\\((https?:\\/\\/[^\\s)]+)\\)/g,'<a class="bitey-inline-link" href="$2" target="_blank" rel="noopener noreferrer">$1</a>');s=s.replace(/^###### (.+)$/gm,'<h6>$1</h6>').replace(/^##### (.+)$/gm,'<h5>$1</h5>').replace(/^#### (.+)$/gm,'<h4>$1</h4>').replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>');s=s.replace(/\\*\\*(.+?)\\*\\*/g,'<strong>$1</strong>').replace(/\\*([^*\\n]+)\\*/g,'<em>$1</em>');const lines=s.split('\\n');let out='',list=null;const flush=()=>{if(list){out+=(list.type==='ol'?'<ol>':'<ul>')+list.items.map(x=>'<li>'+x+'</li>').join('')+(list.type==='ol'?'</ol>':'</ul>');list=null}};for(const line of lines){const m=line.match(/^\\s*[-*]\\s+(.+)$/),o=line.match(/^\\s*\\d+[.)]\\s+(.+)$/);if(m||o){const type=o?'ol':'ul';if(!list||list.type!==type){flush();list={type,items:[]}}list.items.push(m?m[1]:o[1]);continue}if(/^\\s*$/.test(line)){flush();out+='<br>';continue}flush();if(/^<h[1-6]>/.test(line))out+=line;else out+=line+'<br>'}flush();return out.replace(/(?:<br>){2,}/g,'<br><br>').replace(/<br>(?=<h[1-6]>)/g,'').replace(/(<h[1-6]>.*?<\\/h[1-6]>)<br>/g,'$1')}).join('')};const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const save=()=>{if(!state.conversationId)return;const a=load().filter(x=>x.id!==state.conversationId);a.unshift({id:state.conversationId,title:state.title,updatedAt:Date.now()});localStorage.setItem(KEY,JSON.stringify(a.slice(0,100)));renderHistory()};
function renderHistory(){if(!history)return;history.innerHTML='';for(const x of load()){const b=document.createElement('button');b.className='history-item'+(x.id===state.conversationId?' active':'');b.textContent=x.title||'Conversación';b.onclick=()=>openConversation(x.id);history.appendChild(b)}if(!history.children.length){const e=document.createElement('div');e.className='history-empty';e.textContent='Tus conversaciones aparecerán aquí.';history.appendChild(e)}}
const sendIcon='<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="m5 12 14-7-3 14-4-6-7-1Z"/><path d="m12 13 7-8"/></svg>';const stopIcon='<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><rect x="7" y="7" width="10" height="10" rx="2"/></svg>';function setActivity(on,label){if(activity){activity.hidden=!on;if(on){state.activityStartedAt=Date.now();state.activityStage=0;state.activityMode=state.mode;activityText.textContent=label||'Bitey IA está trabajando…';if(state.activityTimer)clearInterval(state.activityTimer);if(state.activityStageTimer)clearInterval(state.activityStageTimer);state.activityTimer=setInterval(()=>{if(activityElapsed)activityElapsed.textContent=((Date.now()-state.activityStartedAt)/1000).toFixed(1).replace('.',',')+' s'},100);state.activityStageTimer=null}}if(!on&&state.activityTimer){clearInterval(state.activityTimer);state.activityTimer=null}if(!on&&state.activityStageTimer){clearInterval(state.activityStageTimer);state.activityStageTimer=null}if(send){send.disabled=false;send.innerHTML=on?stopIcon:sendIcon;send.setAttribute('aria-label',on?'Detener generación':'Enviar mensaje');send.title=on?'Detener generación':'Enviar mensaje'}}function stopActivityPolling(){if(state.activityPollTimer){clearInterval(state.activityPollTimer);state.activityPollTimer=null}}
function startActivityPolling(requestId){stopActivityPolling();if(!requestId)return;const poll=async()=>{try{const r=await fetch(API_BASE+'/api/v2/chat/activity/'+encodeURIComponent(requestId),{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)return;const d=await r.json();if(d.found){updateActivityFromEvents(d.activities||[]);if(activityText&&d.stage&&d.final_status==='running'){const labels={ANALYZING:'Analizando la solicitud…',ROUTING:'Seleccionando capacidades…',SEARCHING_WEB:'Buscando información en la web…',FETCHING_SOURCE:'Verificando fuentes…',VALIDATING_EVIDENCE:'Contrastando evidencia…',REASONING:'Procesando la información…',GENERATING:'Generando la respuesta…',EVALUATING:'Evaluando la respuesta…'};activityText.textContent=labels[d.stage]||d.activities?.at(-1)||'Bitey IA está trabajando…'}}}catch(_){}};poll();state.activityPollTimer=setInterval(poll,650)}
function updateActivityFromEvents(items){const list=(items||[]).map(x=>{if(typeof x==='string')return x;return x?.message||x?.label||x?.text||x?.event||''}).map(x=>String(x||'').replace(/\s+/g,' ').trim()).filter(Boolean);if(!list.length)return;const latest=list[list.length-1];if(activityText)activityText.textContent=latest;showEvents(list)}
function renderResearchSummary(extra){if(!extra)return '';const sources=Array.isArray(extra.sources)?extra.sources.filter(s=>s&&s.url):[];const evidence=extra.evidence_analysis||{};const validation=extra.answer_validation||{};if(!sources.length&&!Object.keys(evidence).length&&!Object.keys(validation).length)return '';const box=document.createElement('div');box.className='research-summary';const title=document.createElement('div');title.className='research-summary-title';title.textContent=sources.length?'Investigación y verificación':'Verificación';box.appendChild(title);if(sources.length){const meta=document.createElement('div');meta.className='research-summary-meta';meta.textContent=sources.length+' fuente'+(sources.length===1?'':'s')+' utilizada'+(sources.length===1?'':'s');box.appendChild(meta)}if(validation.valid===true){const ok=document.createElement('div');ok.className='research-summary-status';ok.textContent='✓ Respuesta validada';box.appendChild(ok)}else if(Number(evidence.contradiction_count||0)>0){const warn=document.createElement('div');warn.className='research-summary-status warning';warn.textContent='⚠ Se detectaron posibles conflictos entre fuentes';box.appendChild(warn)}return box}
function renderCognitivePlan(plan){
  if(!eventsBox||!Array.isArray(plan)||!plan.length)return;
  const safe=plan.map(x=>({stage:String(x?.stage||'').trim(),action:String(x?.action||'').trim()})).filter(x=>x.stage&&x.action).slice(0,8);
  if(!safe.length)return;
  const labels={ANALYZE:'Analizando',ROUTE:'Seleccionando capacidades',RESEARCH:'Investigando',VERIFY:'Verificando',GENERATE:'Generando',EVALUATE:'Evaluando'};
  const existing=[...eventsBox.querySelectorAll('.activity-event')].map(x=>x.textContent.trim().toLowerCase());
  for(const item of safe){
    const label=labels[item.stage]||item.stage;
    const textValue=label+': '+item.action;
    if(existing.includes(textValue.toLowerCase()))continue;
    const d=document.createElement('div');
    d.className='activity-event cognitive-plan-event';
    d.innerHTML='<span class="activity-event-dot"></span><span>'+esc(textValue)+'</span>';
    eventsBox.appendChild(d);
  }
  eventsBox.hidden=false;
}
function showEvents(items){if(!eventsBox)return;eventsBox.innerHTML='';const seen=new Set();const list=(items||[]).map(x=>String(x||'').replace(/\\s+/g,' ').trim()).filter(Boolean).filter(item=>{const key=item.toLocaleLowerCase();if(seen.has(key))return false;seen.add(key);return true}).slice(0,8);for(const item of list){const d=document.createElement('div');d.className='activity-event';d.innerHTML='<span class="activity-event-dot"></span><span>'+esc(item)+'</span>';eventsBox.appendChild(d)}eventsBox.hidden=!list.length;eventsBox.setAttribute('aria-hidden',String(!list.length))}
function renderValidation(extra){
  if(!extra?.answer_validation)return '';
  const v=extra.answer_validation;
  const contradictions=Number(extra?.evidence_analysis?.contradiction_count||0);
  const partial=Number(v.partial_claims||0);
  const unsupported=Number(v.unsupported_claims||0);
  if(v.valid&&!contradictions&&!partial)return '<div class="answer-validation"><span class="answer-validation-dot"></span><span>Respuesta verificada</span></div>';
  if(contradictions)return '<div class="answer-validation warning"><span class="answer-validation-dot"></span><span>Se detectaron '+contradictions+' posible'+(contradictions===1?' conflicto':'s conflictos')+' entre fuentes</span></div>';
  if(unsupported)return '<div class="answer-validation warning"><span class="answer-validation-dot"></span><span>'+unsupported+' afirmación'+(unsupported===1?' requiere':'es requieren')+' revisión</span></div>';
  if(partial)return '<div class="answer-validation warning"><span class="answer-validation-dot"></span><span>'+partial+' afirmación'+(partial===1?' tiene':'es tienen')+' respaldo parcial</span></div>';
  return '<div class="answer-validation warning"><span class="answer-validation-dot"></span><span>Respuesta entregada con incertidumbre</span></div>';
}
function addMessage(role,text,extra,meta={}){const row=document.createElement('article');row.className='message '+role;if(meta.prompt)row.dataset.prompt=String(meta.prompt);const body=document.createElement('div');body.className='message-content';body.innerHTML=role==='assistant'?renderText(clean(text)):esc(text).replace(/\n/g,'<br>');row.appendChild(body);if(role==='assistant'&&extra){state.lastAnswer=String(text||'');state.lastAnswerExtra=extra;const validation=renderValidation(extra);if(validation){const box=document.createElement('div');box.className='answer-validation-wrap';box.innerHTML=validation;row.appendChild(box)}const researchSummary=renderResearchSummary(extra);if(researchSummary)row.appendChild(researchSummary);}if(role==='assistant'&&text){const actions=document.createElement('div');actions.className='answer-actions';const copy=document.createElement('button');copy.type='button';copy.className='answer-action';copy.textContent='Copiar';copy.title='Copiar respuesta';copy.onclick=async()=>{try{await navigator.clipboard.writeText(String(text||''));copy.textContent='Copiado';setTimeout(()=>copy.textContent='Copiar',1200)}catch(_){copy.textContent='No disponible'}};actions.appendChild(copy);const regen=document.createElement('button');regen.type='button';regen.className='answer-action';regen.textContent='Regenerar';regen.title='Regenerar esta respuesta';regen.onclick=()=>{const prompt=row.dataset.prompt||'';if(!state.busy&&prompt)regenerateMessage(row,prompt)};actions.appendChild(regen);row.appendChild(actions)}if(extra&&Array.isArray(extra.sources)&&extra.sources.length){const seen=new Set();const sources=extra.sources.filter(s=>s&&s.url).filter(s=>{const key=String(s.url).trim().toLowerCase();if(seen.has(key))return false;seen.add(key);return true}).slice(0,8);if(sources.length){const box=document.createElement('div');box.className='bitey-sources';const title=document.createElement('div');title.className='bitey-sources-title';title.textContent=sources.length===1?'Fuente verificada':'Fuentes verificadas';box.appendChild(title);sources.forEach((s,i)=>{const a=document.createElement('a');a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='[S'+(i+1)+'] '+(s.title||s.url);box.appendChild(a)});row.appendChild(box)}}messages.appendChild(row);row.scrollIntoView({behavior:'smooth',block:'end'})}
function reset(){state.conversationId=null;state.title='Nueva conversación';state.attachments=[];messages.innerHTML='<div class="welcome"><img class="bitey-logo" src="./bitey-logo.svg" alt="Bitey IA"/><div class="eyebrow">Bitey IA</div><h1>Hola, soy Bitey.</h1><p class="hero-copy">¿En qué estás pensando?</p><div class="starter-row"><button data-starter="Investiga este tema y explícamelo">Investigar</button><button data-starter="Ayúdame a crear una solución">Crear</button><button data-starter="Ayúdame a analizar esta idea">Analizar</button></div></div>';bindStarters();renderHistory();input?.focus()}
async function openConversation(id){try{const r=await fetch(API_BASE+'/api/v1/conversations/'+encodeURIComponent(id)+'/messages');if(!r.ok)throw Error('history_'+r.status);const d=await r.json();state.conversationId=id;const item=load().find(x=>x.id===id);state.title=item?.title||'Conversación';messages.innerHTML='';for(const m of d.messages||[])if(m.role==='user'||m.role==='assistant')addMessage(m.role,m.content,{});renderHistory()}catch(e){console.error(e)}}
function autoModeFor(text){if(state.mode!=='auto')return state.mode;const s=String(text||'').toLowerCase().trim();const explicitResearch=/\b(busca|buscar|búsqueda|investiga|investigar|investigación|fuentes|compara|comparar|comparativa|contrasta|alternativas|opciones|recomienda|recomendaciones|search|research)\b/.test(s);const currentInfo=/\b(hoy|ahora|actual(?:mente)?|actualizado|últim[oa]s?|latest|noticia|noticias|news|precio|precios|cotización|cotiza|cuánto cuesta|quién es|quien es|dónde está|donde está|qué pasó|que paso|mercado|acciones|dólar|dolar|euro|bitcoin|resultados)\b/.test(s);const math=/\b(calcula|calcular|cálculo|calculo|ecuación|ecuacion|porcentaje|interés|interes|probabilidad|estadística|estadistica|matriz|derivada|integral|álgebra|algebra|cuánto es|cuanto es)\b/.test(s)||/[=+*/^√∑]/.test(s);const code=/\b(código|codigo|python|javascript|typescript|html|css|sql|bug|error|stack trace|api|regex|función|funcion|programa|programar|debug)\b/.test(s);if(code)return 'code';if(math&&!currentInfo)return 'math';if(explicitResearch||currentInfo)return 'research';return 'chat'}
async function sendMessage(raw,options={}){const text=String(raw||'').trim();if(!text)return;if(state.busy){state.abortController?.abort();return}state.busy=true;state.lastPrompt=text;const effectiveMode=autoModeFor(text);state.abortController=new AbortController();const requestId=createRequestId();setActivity(true,options.regenerate?'Bitey IA está regenerando la respuesta…':effectiveMode==='research'?'Bitey IA está investigando y contrastando información…':effectiveMode==='math'?'Bitey IA está calculando y comprobando el resultado…':effectiveMode==='code'?'Bitey IA está analizando el código…':'Bitey IA está procesando tu solicitud…');showEvents([]);startActivityPolling(requestId);if(messages.querySelector('.welcome'))messages.innerHTML='';if(!options.regenerate)addMessage('user',text,{},{});input.value='';input.style.height='auto';if(state.title==='Nueva conversación')state.title=text.slice(0,60);try{let r=null,d=null;for(let attempt=0;attempt<2;attempt++){try{r=await fetch(API_BASE+'/api/v2/chat',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({conversation_id:state.conversationId,message:text,mode:effectiveMode,metadata:{channel:'web',interface:'bitey-web-v2',request_id:requestId,regenerate:Boolean(options.regenerate),language:navigator.language||'es',attachments:(window.BiteyAttachments?.()||state.attachments||[]).map(x=>({name:x.name,type:x.type,size:x.size}))}}),signal:state.abortController.signal});if(!r.ok&&[502,503,504].includes(r.status)&&attempt===0){await new Promise(resolve=>setTimeout(resolve,900));continue}d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||d.error||('HTTP '+r.status));break}catch(err){if(attempt===0&&/Failed to fetch|NetworkError|HTTP 502|HTTP 503|HTTP 504/i.test(String(err?.message||err))){await new Promise(resolve=>setTimeout(resolve,900));continue}throw err}}if(!r||!r.ok)throw Error(d?.detail||d?.error||'No se recibió una respuesta válida del servidor');state.conversationId=d.conversation_id;stopActivityPolling();const answerExtra={sources:d.sources,answer_validation:d.answer_validation,evidence_analysis:d.evidence_analysis,cognitive_plan:d.cognitive_plan||[]};addMessage('assistant',clean(d.answer)||'No recibí una respuesta pública válida.',answerExtra,{prompt:text});updateActivityFromEvents(d.activity_events||[]);renderCognitivePlan(d.cognitive_plan||[]);if(activityText)activityText.textContent='Bitey IA preparó la respuesta';save()}catch(e){if(e?.name==='AbortError'){showEvents(['Generación detenida por el usuario.']);addMessage('assistant','Generación detenida. Puedes volver a intentarlo.',{})}else{addMessage('assistant','No pude completar la solicitud en este momento. La conversación se conserva para reintentar.',{});showEvents([String(e.message||e)])}}finally{stopActivityPolling();state.busy=false;state.abortController=null;setActivity(false);input?.focus()}}
function regenerateMessage(row,prompt){if(!row||!prompt||state.busy)return;row.remove();sendMessage(prompt,{regenerate:true})}
function bindStarters(){document.querySelectorAll('[data-starter]').forEach(b=>b.onclick=()=>{input.value=b.dataset.starter;form.requestSubmit()})}
function installModeSelector(){if(!input||$('#bitey-mode'))return;const wrap=document.createElement('select');wrap.id='bitey-mode';wrap.title='Modo de Bitey IA';[['auto','Auto'],['chat','Chat'],['research','Investigación'],['math','Matemática'],['code','Código']].forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;wrap.appendChild(o)});wrap.onchange=()=>state.mode=wrap.value;wrap.className='bitey-mode';$('.composer')?.appendChild(wrap)}
if(form)form.onsubmit=e=>{e.preventDefault();sendMessage(input.value)};if($('#new-chat'))$('#new-chat').onclick=reset;if(input)input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}};input?.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,180)+'px'});installModeSelector();bindStarters();renderHistory();window.BiteyChatV2={sendMessage,reset,openConversation,retry:()=>state.lastPrompt?sendMessage(state.lastPrompt):null,regenerateMessage,stop:()=>state.abortController?.abort()};
})();