(function(){
  const U='https://vttwfnnfcoavdhzeiqwl.supabase.co',K='sb_publishable_ewRqbdjRDJM8wmz-qdaPBA_tvj72lwK6';
  const L={es:{name:'Español',login:'Entrar en Bitey IA',register:'Crear cuenta',email:'Correo electrónico',password:'Contraseña',enter:'Entrar',create:'Crear cuenta',verifyEmail:'Revisa tu correo para confirmar la cuenta.',forgot:'¿Olvidaste tu contraseña?',two:'Verificación en dos pasos',code:'Código de 6 dígitos',verify:'Verificar',enable:'Activar 2FA',disable:'Desactivar 2FA',scan:'Escanea el QR con tu app autenticadora y escribe el código.',account:'Mi cuenta',connected:'Cuenta conectada',logout:'Cerrar sesión',language:'Idioma',close:'Cerrar'},pt:{name:'Português',login:'Entrar no Bitey IA',register:'Criar conta',email:'E-mail',password:'Senha',enter:'Entrar',create:'Criar conta',verifyEmail:'Verifique seu e-mail para confirmar a conta.',forgot:'Esqueceu sua senha?',two:'Verificação em duas etapas',code:'Código de 6 dígitos',verify:'Verificar',enable:'Ativar 2FA',disable:'Desativar 2FA',scan:'Escaneie o QR no seu app autenticador e digite o código.',account:'Minha conta',connected:'Conta conectada',logout:'Sair',language:'Idioma',close:'Fechar'},en:{name:'English',login:'Sign in to Bitey IA',register:'Create account',email:'Email',password:'Password',enter:'Sign in',create:'Create account',verifyEmail:'Check your email to confirm the account.',forgot:'Forgot your password?',two:'Two-step verification',code:'6-digit code',verify:'Verify',enable:'Enable 2FA',disable:'Disable 2FA',scan:'Scan the QR with your authenticator app and enter the code.',account:'My account',connected:'Account connected',logout:'Sign out',language:'Language',close:'Close'}};
  let c=null,s=null,lang=localStorage.getItem('bitey-language')||((navigator.language||'es').slice(0,2));if(!L[lang])lang='es';const t=k=>(L[lang]||L.es)[k]||k;
  const q=x=>document.querySelector(x);
  function client(){if(!window.supabase)return null;return c||(c=window.supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}))}
  function style(){if(q('#bitey-auth-i18n-style'))return;const st=document.createElement('style');st.id='bitey-auth-i18n-style';st.textContent='.bitey-global-tools{display:flex;gap:8px;align-items:center;margin-left:8px}.bitey-language{border:1px solid var(--line,#263444);background:var(--panel,#0b1016);color:inherit;border-radius:9px;padding:7px 9px}.auth-mfa-qr{display:block;width:min(220px,100%);margin:12px auto;background:#fff;border-radius:8px;padding:8px}.auth-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.auth-actions button{cursor:pointer}.auth-status{min-height:20px}';document.head.appendChild(st)}
  function modal(){if(q('#bitey-auth-modal'))return;const e=document.createElement('div');e.id='bitey-auth-modal';e.className='modal-backdrop';e.innerHTML='<div class="modal auth-modal"><button class="auth-close" type="button">×</button><img class="auth-logo" src="./bitey-logo.svg" alt="Bitey IA" width="180" height="180"><div class="auth-brand">Bitey IA</div><h2 id="auth-title"></h2><p id="auth-subtitle"></p><div id="auth-content"></div></div>';document.body.appendChild(e);q('.auth-close').onclick=()=>e.classList.remove('open');}
  function language(){if(q('.bitey-global-tools'))return;const target=q('.topbar')||q('header')||q('.nav');if(!target)return;const wrap=document.createElement('div');wrap.className='bitey-global-tools';wrap.innerHTML='<select class="bitey-language" aria-label="'+t('language')+'">'+Object.entries(L).map(([k,v])=>'<option value="'+k+'" '+(k===lang?'selected':'')+'>'+v.name+'</option>').join('')+'</select>';target.appendChild(wrap);wrap.querySelector('select').onchange=e=>{lang=e.target.value;localStorage.setItem('bitey-language',lang);document.documentElement.lang=lang;window.dispatchEvent(new CustomEvent('bitey:language',{detail:{language:lang}}));render()};}
  function open(){modal();render();q('#bitey-auth-modal').classList.add('open')}
  async function render(){style();modal();const e=q('#bitey-auth-modal'),title=q('#auth-title'),sub=q('#auth-subtitle'),body=q('#auth-content');if(!body)return;document.documentElement.lang=lang;if(!s){title.textContent=t('login');sub.textContent=t('connected');body.innerHTML='<form id="auth-form"><label>'+t('email')+'<input id="auth-email" type="email" required autocomplete="email"></label><label>'+t('password')+'<input id="auth-password" type="password" required minlength="6" autocomplete="current-password"></label><div class="auth-actions"><button id="auth-submit" class="send-button auth-submit" type="submit">'+t('enter')+'</button><button id="auth-switch" class="auth-secondary" type="button">'+t('register')+'</button></div></form><button id="auth-reset" class="auth-link" type="button">'+t('forgot')+'</button><p id="auth-status" class="auth-status"></p>';let up=false;q('#auth-switch').onclick=()=>{up=!up;title.textContent=up?t('register'):t('login');q('#auth-submit').textContent=up?t('create'):t('enter');q('#auth-switch').textContent=up?t('enter'):t('register');q('#auth-password').autocomplete=up?'new-password':'current-password';q('#auth-form').onsubmit=ev=>{ev.preventDefault();void submit(up)}};q('#auth-form').onsubmit=ev=>{ev.preventDefault();void submit(false)};q('#auth-reset').onclick=reset;}else{title.textContent=t('account');sub.textContent=s.user.email;body.innerHTML='<p><b>'+t('two')+'</b></p><div id="auth-mfa"></div><div class="auth-actions"><button id="auth-logout" class="auth-secondary">'+t('logout')+'</button></div>';q('#auth-logout').onclick=async()=>{await client().auth.signOut();s=null;render();profile()};void mfa()} }
  async function submit(up){const x=client(),email=q('#auth-email').value.trim(),password=q('#auth-password').value,st=q('#auth-status');if(st)st.textContent='…';const r=up?await x.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname,data:{language:lang,product:'bitey-web'}}}):await x.auth.signInWithPassword({email,password});if(r.error){if(st)st.textContent=r.error.message;return}if(up&&!r.data.session){if(st)st.textContent=t('verifyEmail');return}s=r.data.session;const f=await x.auth.mfa.listFactors(),v=(f.data?.totp||[]).find(z=>z.status==='verified');if(v){const ch=await x.auth.mfa.challenge({factorId:v.id});return challenge(v.id,ch.data?.id)}render();profile()}
  async function challenge(fid,cid){const body=q('#auth-content');body.innerHTML='<p><b>'+t('two')+'</b></p><p>'+t('code')+'</p><input id="auth-mfa-code" inputmode="numeric" maxlength="6" autocomplete="one-time-code"><div class="auth-actions"><button id="auth-mfa-verify" class="send-button">'+t('verify')+'</button></div><p id="auth-status" class="auth-status"></p>';q('#auth-mfa-verify').onclick=async()=>{const r=await client().auth.mfa.verify({factorId:fid,challengeId:cid,code:q('#auth-mfa-code').value.trim()});if(r.error){q('#auth-status').textContent=r.error.message;return}s=r.data.session;render();profile()}}
  async function mfa(){const box=q('#auth-mfa');if(!box)return;const x=client(),r=await x.auth.mfa.listFactors(),v=(r.data?.totp||[]).find(z=>z.status==='verified');if(v){box.innerHTML='<p>✓ '+t('two')+'</p><button id="auth-disable" class="auth-secondary">'+t('disable')+'</button>';q('#auth-disable').onclick=async()=>{const z=await x.auth.mfa.unenroll({factorId:v.id});if(z.error){box.textContent=z.error.message;return}render()};return}box.innerHTML='<button id="auth-enable" class="send-button">'+t('enable')+'</button>';q('#auth-enable').onclick=async()=>{const z=await x.auth.mfa.enroll({factorType:'totp',friendlyName:'Bitey IA'});if(z.error){box.textContent=z.error.message;return}box.innerHTML='<p>'+t('scan')+'</p><img class="auth-mfa-qr" src="'+z.data.totp.qr_code+'" alt="TOTP QR"><input id="auth-enroll-code" inputmode="numeric" maxlength="6" autocomplete="one-time-code"><div class="auth-actions"><button id="auth-enroll-verify" class="send-button">'+t('verify')+'</button></div><p id="auth-status" class="auth-status"></p>';q('#auth-enroll-verify').onclick=async()=>{const ch=await x.auth.mfa.challenge({factorId:z.data.id});const v2=await x.auth.mfa.verify({factorId:z.data.id,challengeId:ch.data.id,code:q('#auth-enroll-code').value.trim()});if(v2.error){q('#auth-status').textContent=v2.error.message;return}s=v2.data.session;render()}}}
  async function reset(){const email=q('#auth-email')?.value.trim()||prompt(t('email'));if(!email)return;const r=await client().auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});q('#auth-status').textContent=r.error?r.error.message:'Password reset email sent.'}
  function profile(){document.querySelectorAll('.profile-copy strong,.profile-menu-head strong').forEach(x=>x.textContent=s?.user?.user_metadata?.full_name||s?.user?.email||'Bitey IA');document.querySelectorAll('.profile-copy small,.profile-menu-head small').forEach(x=>x.textContent=s?t('connected'):t('login'));document.querySelectorAll('.profile-avatar').forEach(x=>x.textContent=s?(s.user.email||'U').charAt(0).toUpperCase():'B')}
  function boot(){style();modal();language();const x=client();if(!x)return;void x.auth.getSession().then(r=>{s=r.data.session;profile()});x.auth.onAuthStateChange((_e,z)=>{s=z;profile()});const f=window.fetch;window.fetch=async function(i,o={}){const u=typeof i==='string'?i:i?.url||'';if(s?.access_token&&u.includes('/api/v1/'))o={...o,headers:{...(o.headers||{}),Authorization:'Bearer '+s.access_token}};return f(i,o)};window.BiteyAuth={getSession:()=>s,open,signOut:async()=>{await x.auth.signOut();location.reload()},setLanguage:v=>{if(L[v]){lang=v;localStorage.setItem('bitey-language',v);render()}}};if(location.pathname.replace(/\/+$/,'')==='/conectate'&&!s)open();document.querySelector('[data-profile="account"]')?.addEventListener('click',()=>{if(!s)open()})}
  window.addEventListener('DOMContentLoaded',boot,{once:true});
})();
