(() => {
  const K={projects:'bitey_projects_v1',library:'bitey_library_v1',settings:'bitey_settings_v1',profile:'bitey_profile_v1',tools:'bitey_tools_v1',memory:'bitey_memory_v1'};
  const read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const modal=()=>document.getElementById('modal-backdrop'),body=()=>document.getElementById('modal-body'),bs=id=>document.getElementById(id);
  function open(t,x,h=''){const b=modal();if(!b)return;document.getElementById('modal-title').textContent=t;document.getElementById('modal-text').textContent=x||'';if(body())body().innerHTML=h;b.classList.add('open')}
  function close(){modal()?.classList.remove('open')}
  function projects(){const a=read(K.projects);open('Proyectos','Cada proyecto mantiene su propio contexto.',`<div class="feature-list">${a.map(p=>`<button class="feature-row" data-pid="${esc(p.id)}"><span>◇</span><span><b>${esc(p.name)}</b><small>${esc(p.description||'Proyecto de Bitey IA')}</small></span></button>`).join('')||'<p class="muted">No hay proyectos todavía.</p>'}</div><button class="primary-action" id="new-project">＋ Nuevo proyecto</button>`);body()?.querySelectorAll('[data-pid]').forEach(b=>b.onclick=()=>{window.BiteyProjectId=b.dataset.pid;close();document.getElementById('new-chat')?.click()});document.getElementById('new-project')?.addEventListener('click',()=>{const n=window.prompt('Nombre del proyecto');if(!n?.trim())return;const p=read(K.projects);p.unshift({id:crypto.randomUUID(),name:n.trim(),createdAt:Date.now()});write(K.projects,p);projects()})}
  function library(){const a=read(K.library);open('Biblioteca','Archivos reutilizables como contexto.',`<div class="feature-list">${a.map(f=>`<div class="feature-row"><span>▣</span><span><b>${esc(f.name)}</b><small>${esc(f.type||'archivo')} · ${Math.ceil((f.size||0)/1024)} KB</small></span></div>`).join('')||'<p class="muted">La Biblioteca está vacía.</p>'}</div><label class="primary-action upload-action">＋ Añadir archivos<input id="bitey-files" type="file" multiple hidden></label>`);document.getElementById('bitey-files')?.addEventListener('change',e=>{const a=read(K.library);[...e.target.files].forEach(f=>a.unshift({id:crypto.randomUUID(),name:f.name,type:f.type,size:f.size,createdAt:Date.now()}));write(K.library,a.slice(0,200));library()})}
  function settings(){const s={language:'auto',appearance:'system',memory:true,webSearch:true,...read(K.settings,{})};open('Configuración','Preferencias de Bitey IA.',`<div class="settings-form"><label>Idioma<select id="bs-lang"><option value="auto">Automático</option><option value="es">Español</option><option value="pt-BR">Português</option><option value="en">English</option></select></label><label>Apariencia<select id="bs-theme"><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Oscuro</option></select></label><label><input id="bs-memory" type="checkbox"> Memoria</label><label><input id="bs-web" type="checkbox"> Búsqueda web automática</label><button class="primary-action" id="bs-save">Guardar</button></div>`);bs('bs-lang').value=s.language;bs('bs-theme').value=s.appearance;bs('bs-memory').checked=s.memory;bs('bs-web').checked=s.webSearch;bs('bs-save').onclick=()=>{const n={language:bs('bs-lang').value,appearance:bs('bs-theme').value,memory:bs('bs-memory').checked,webSearch:bs('bs-web').checked};write(K.settings,n);document.documentElement.dataset.appearance=n.appearance;close()}}
  function toggleTool(name){const t={...read(K.tools,{web:false,research:false}),[name]:!read(K.tools,{web:false,research:false})[name]};write(K.tools,t);open('Explorar IA',`${name==='web'?'Búsqueda web':'Investigación profunda'} ${t[name]?'activada':'desactivada'}.`,`<p class="muted">La preferencia quedó guardada para este navegador.</p><button class="primary-action" id="tools-close">Continuar</button>`);bs('tools-close').onclick=close}
  function tools(){const t=read(K.tools,{web:false,research:false});open('Explorar IA','Selecciona una capacidad para la conversación.',`<div class="feature-list"><button class="feature-row" id="tool-web"><span>⌕</span><span><b>Búsqueda web</b><small>${t.web?'Activada':'Activada al seleccionarla'}</small></span></button><button class="feature-row" id="tool-research"><span>✦</span><span><b>Investigación profunda</b><small>${t.research?'Activada':'Activada al seleccionarla'}</small></span></button><button class="feature-row" id="tool-attach"><span>▣</span><span><b>Archivos</b><small>Añadir contexto a la conversación</small></span></button></div>`);bs('tool-web').onclick=()=>toggleTool('web');bs('tool-research').onclick=()=>toggleTool('research');bs('tool-attach').onclick=()=>bs('file-input')?.click()}
  function profileAction(type){
    if(type==='account')open('Cuenta','Gestiona identidad, datos y sesiones.','<div class="feature-list"><div class="feature-row"><span>◉</span><span><b>Perfil de Bitey IA</b><small>Cuenta preparada para identidad de usuario.</small></span></div><div class="feature-row"><span>⌁</span><span><b>Sesiones</b><small>Gestiona las sesiones desde tu cuenta.</small></span></div></div>');
    else if(type==='personalize'){const p={tone:'Equilibrado',language:'Automático',proactive:false,...read(K.profile,{})};open('Personalización','Define cómo quieres que Bitey interactúe contigo.',`<div class="settings-form"><label>Tono<select id="p-tone"><option>Equilibrado</option><option>Profesional</option><option>Directo</option><option>Creativo</option></select></label><label>Idioma<select id="p-lang"><option>Automático</option><option>Español</option><option>Português</option><option>English</option></select></label><label><input id="p-proactive" type="checkbox"> Sugerencias proactivas</label><button class="primary-action" id="p-save">Guardar preferencias</button></div>`);bs('p-tone').value=p.tone;bs('p-lang').value=p.language;bs('p-proactive').checked=!!p.proactive;bs('p-save').onclick=()=>{write(K.profile,{tone:bs('p-tone').value,language:bs('p-lang').value,proactive:bs('p-proactive').checked});close()}}
    else if(type==='memory'){const m={enabled:true,...read(K.memory,{})};open('Memoria','Controla lo que Bitey puede recordar.',`<div class="settings-form"><label><input id="memory-enabled" type="checkbox"> Memoria activada</label><p class="muted">La memoria se aplicará cuando el backend de Bitey la soporte para esta sesión.</p><button class="primary-action" id="memory-save">Guardar</button></div>`);bs('memory-enabled').checked=!!m.enabled;bs('memory-save').onclick=()=>{write(K.memory,{enabled:bs('memory-enabled').checked});close()}}
    else if(type==='settings')settings();
    else open('Ayuda','Cómo usar Bitey IA.','<p>Usa ＋ para añadir contenido, 🎙️ para voz y el menú lateral para explorar Bitey.</p>');
  }
  window.BiteyUI={projects,library,settings,tools,profileAction,close};
})();
