(() => {
  const K={projects:'bitey_projects_v1',library:'bitey_library_v1',settings:'bitey_settings_v1'};
  const read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const modal=()=>document.getElementById('modal-backdrop'), body=()=>document.getElementById('modal-body');
  function open(t,x,h=''){document.getElementById('modal-title').textContent=t;document.getElementById('modal-text').textContent=x||'';if(body())body().innerHTML=h;modal().classList.add('open')}
  function close(){modal().classList.remove('open')}
  function projects(){const a=read(K.projects);open('Proyectos','Cada proyecto mantiene su propio contexto.',`<div class="feature-list">${a.map(p=>`<button class="feature-row" data-pid="${esc(p.id)}"><span>◇</span><span><b>${esc(p.name)}</b><small>${esc(p.description||'Proyecto de Bitey IA')}</small></span></button>`).join('')||'<p class="muted">No hay proyectos todavía.</p>'}</div><button class="primary-action" id="new-project">＋ Nuevo proyecto</button>`);body().querySelectorAll('[data-pid]').forEach(b=>b.onclick=()=>{window.BiteyProjectId=b.dataset.pid;close();document.getElementById('new-chat')?.click()});document.getElementById('new-project')?.addEventListener('click',()=>{const n=prompt('Nombre del proyecto');if(!n?.trim())return;const p=read(K.projects);p.unshift({id:crypto.randomUUID(),name:n.trim(),createdAt:Date.now()});write(K.projects,p);projects()})}
  function library(){const a=read(K.library);open('Biblioteca','Archivos reutilizables como contexto.',`<div class="feature-list">${a.map(f=>`<div class="feature-row"><span>▣</span><span><b>${esc(f.name)}</b><small>${esc(f.type||'archivo')} · ${Math.ceil((f.size||0)/1024)} KB</small></span></div>`).join('')||'<p class="muted">La Biblioteca está vacía.</p>'}</div><label class="primary-action upload-action">＋ Añadir archivos<input id="bitey-files" type="file" multiple hidden></label>`);document.getElementById('bitey-files')?.addEventListener('change',e=>{const a=read(K.library);[...e.target.files].forEach(f=>a.unshift({id:crypto.randomUUID(),name:f.name,type:f.type,size:f.size,createdAt:Date.now()}));write(K.library,a.slice(0,200));library()})}
  function settings(){const s={language:'auto',appearance:'system',memory:true,webSearch:true,...read(K.settings,{})};open('Configuración','Preferencias del Supracerebro.',`<div class="settings-form"><label>Idioma<select id="bs-lang"><option value="auto">Automático</option><option value="es">Español</option><option value="pt-BR">Português</option><option value="en">English</option></select></label><label>Apariencia<select id="bs-theme"><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Oscuro</option></select></label><label><input id="bs-memory" type="checkbox"> Memoria</label><label><input id="bs-web" type="checkbox"> Búsqueda web automática</label><button class="primary-action" id="bs-save">Guardar</button></div>`);bs('bs-lang').value=s.language;bs('bs-theme').value=s.appearance;bs('bs-memory').checked=s.memory;bs('bs-web').checked=s.webSearch;bs('bs-save').onclick=()=>{const n={language:bs('bs-lang').value,appearance:bs('bs-theme').value,memory:bs('bs-memory').checked,webSearch:bs('bs-web').checked};write(K.settings,n);document.documentElement.dataset.appearance=n.appearance;close()}}
  const bs=id=>document.getElementById(id);
  async function tools(){let items=[];try{const r=await fetch('/api/v1/capabilities',{headers:{Accept:'application/json'}});if(r.ok){const d=await r.json();items=Array.isArray(d.tools)?d.tools:[]}}catch{}if(!items.length)items=[{name:'web_research',description:'Investiga fuentes públicas y recupera evidencia.'},{name:'workspace_files',description:'Usa archivos y proyectos como contexto general.'},{name:'calculator',description:'Calcula expresiones matemáticas de forma segura y local.'},{name:'code_reasoning',description:'Analiza código sin ejecutar código arbitrario.'}];const icons={web_research:'⌕',workspace_files:'▣',calculator:'∑',code_reasoning:'⌘'},labels={web_research:'Búsqueda e investigación web',workspace_files:'Archivos y proyectos',calculator:'Calculadora',code_reasoning:'Razonamiento de código'};open('Herramientas','Capacidades reales disponibles en el Supracerebro.',`<div class="feature-list">${items.map(t=>`<button class="feature-row" data-tool="${esc(t.name||'tool')}"><span>${icons[t.name]||'✦'}</span><span><b>${esc(labels[t.name]||t.name)}</b><small>${esc(t.description||'Herramienta general de Bitey IA')} · Disponible</small></span></button>`).join('')}</div><p class="muted">Bitey selecciona automáticamente herramientas cuando la tarea lo requiere.</p>`);body().querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{window.BiteyTools=window.BiteyTools||{};window.BiteyTools[b.dataset.tool]=true;close();if(b.dataset.tool==='workspace_files')bs('file-input')?.click()})}
  document.addEventListener('click',e=>{const p=e.target.closest('[data-panel]');if(p){e.preventDefault();e.stopImmediatePropagation();({library,projects,explore:tools}[p.dataset.panel]||tools)();return}const x=e.target.closest('#settings,#help,#profile');if(x){e.preventDefault();e.stopImmediatePropagation();if(x.id==='settings')settings();else if(x.id==='help')open('Ayuda','Cómo usar Bitey IA.','<p>Escribe en el cuadro central. Usa el menú lateral para conversaciones, proyectos, biblioteca y configuración.</p>');else open('Bitey IA','Supracerebro independiente de BiteFixes Backend.','<p>Los datos y credenciales de BiteFixes permanecen separados.</p>')}},true);
  window.BiteyUI={projects,library,settings,tools};
})();
