(() => {
  const API = () => `${window.BITEY_API_BASE || ''}/api/v1`;
  const ACTIVE_KEY = 'bitey.activeWorkspaceId';
  const modal = () => document.getElementById('modal-backdrop');
  const body = () => document.getElementById('modal-body');
  const esc = s => String(s ?? '').replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const activeId = () => { try { return localStorage.getItem(ACTIVE_KEY) || ''; } catch { return ''; } };
  const setActive = id => { try { if(id)localStorage.setItem(ACTIVE_KEY,id); else localStorage.removeItem(ACTIVE_KEY); } catch {} window.dispatchEvent(new CustomEvent('bitey:workspace-changed',{detail:{id:id||''}})); };
  const pickWorkspace = ws => ws.find(w => w.id === activeId()) || ws[0] || null;
  const open = (title, text, html='') => { const m=modal(); if(!m)return; document.getElementById('modal-title').textContent=title; document.getElementById('modal-text').textContent=text; body().innerHTML=html; m.classList.add('open'); };
  async function catalog(){try{const r=await fetch(`${API()}/workspace/catalog`);return r.ok?await r.json():null;}catch{return null;}}
  async function workspaces(){try{const r=await fetch(`${API()}/workspaces`);return r.ok?(await r.json()).workspaces||[]:[];}catch{return [];}}
  async function getWorkspace(id){try{const r=await fetch(`${API()}/workspaces/${encodeURIComponent(id)}`);return r.ok?await r.json():null;}catch{return null;}}
  async function createWorkspace(name,description=''){try{const r=await fetch(`${API()}/workspaces`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,description})});return r.ok?r.json():null;}catch{return null;}}
  async function inspectCognitive(prompt,capability,context={}){try{const r=await fetch(`${API()}/workspace/cognitive/inspect`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({prompt,capability,context})});return r.ok?await r.json():null;}catch{return null;}}
  async function createTask(id,capability,prompt){try{const r=await fetch(`${API()}/workspaces/${encodeURIComponent(id)}/tasks`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:prompt.slice(0,80)||'Nueva tarea',prompt,capability})});return r.ok?r.json():null;}catch{return null;}}
  async function runTask(id,taskId){try{const r=await fetch(`${API()}/workspaces/${encodeURIComponent(id)}/tasks/${encodeURIComponent(taskId)}/run`,{method:'POST',headers:{'Accept':'application/json'}});return r.ok?r.json():null;}catch{return null;}}
  async function recentTasks(id){try{const r=await fetch(`${API()}/workspaces/${encodeURIComponent(id)}/tasks`);return r.ok?(await r.json()).tasks||[]:[];}catch{return [];}}
  function phaseMarkup(plan,phase='planning'){const phases=['Pensando','Planificando','Investigando','Generando','Evaluando','Listo'];const active=phase==='researching'?2:phase==='generating'?3:phase==='evaluating'?4:phase==='completed'?5:1;return `<div class="workspace-cognitive-status"><div class="feature-row"><span>◈</span><span><b>Cerebro cognitivo de Bitey</b><small>${esc(plan?.route==='research'?'Ruta: investigación':plan?.route==='artifact'?'Ruta: creación de artefacto':'Ruta: conversación')}</small></span></div><div class="workspace-phases">${phases.map((p,i)=>`<span class="${i<active?'done ':''}${i===active?'active':''}">${i<active?'✓ ':''}${p}</span>`).join('')}</div></div>`;}
  function traceMarkup(trace){return `<details class="workspace-trace"><summary>Ver ejecución cognitiva</summary><div>${(Array.isArray(trace)?trace:[]).map(x=>`<div class="feature-row"><span>${x.status==='blocked'?'⛔':x.status==='skipped'?'—':'✓'}</span><span><b>${esc(x.phase)}</b><small>${esc(x.detail||x.status)}</small></span></div>`).join('')||'<small>No hay trazabilidad disponible.</small>'}</div></details>`;}
  function artifactContent(a){const c=a?.content;if(c&&typeof c==='object')return String(c.content||JSON.stringify(c,null,2));return String(c||'');}
  function evaluationMarkup(e){e=e||{};return `<section class="workspace-detail-section"><b>Evaluación</b><div class="workspace-detail-grid"><span><small>Decisión</small><strong>${esc(e.decision||'unknown')}</strong></span><span><small>Confianza</small><strong>${esc(e.confidence??'—')}</strong></span></div>${e.reason?`<small>${esc(e.reason)}</small>`:''}</section>`;}
  function detailMarkup(task){const result=task?.result||{};const decision=result.cognitive_decision||{};const evaluation=result.evaluation||{};const research=result.research||{};const artifact=result.artifact||null;const sources=(research.steps||[]).flatMap(s=>Array.isArray(s.sources)?s.sources:[]);const evidence=String(research.evidence_context||'');return `<div class="workspace-result" data-execution="${esc(JSON.stringify(result))}">${phaseMarkup(decision,'completed')}<div class="workspace-detail-section"><b>Plan cognitivo</b><div class="workspace-detail-grid"><span><small>Intención</small><strong>${esc(decision.task_class||decision.intention||'—')}</strong></span><span><small>Modo</small><strong>${esc(decision.reasoning_mode||'—')}</strong></span><span><small>Riesgo</small><strong>${esc(decision.risk_level||'—')}</strong></span><span><small>Evidencia</small><strong>${decision.evidence_required?'requerida':'no requerida'}</strong></span></div></div>${artifact?`<section class="workspace-detail-section"><b>Resultado / artefacto</b><small>${esc(artifact.artifact_type||'artifact')} · ${esc(artifact.status||'ready')}</small><pre class="workspace-evidence">${esc(artifactContent(artifact).slice(0,20000)||'Sin contenido visible.')}</pre></section>`:''}${research&&Object.keys(research).length?`<section class="workspace-detail-section"><b>Evidencia</b><small>${(research.steps||[]).length} pasos · ${sources.length} fuentes registradas</small><pre class="workspace-evidence">${esc(evidence.slice(0,12000)||'Sin evidencia textual recuperada.')}</pre></section>`:''}${result.answer?`<section class="workspace-detail-section"><b>Respuesta</b><pre class="workspace-evidence">${esc(String(result.answer).slice(0,16000))}</pre></section>`:''}${evaluationMarkup(evaluation)}${traceMarkup(result.execution_trace)}</div>`;}
  function taskHistoryMarkup(items){return `<div class="workspace-history"><b>Actividad reciente</b>${(items||[]).slice(0,8).map(t=>`<button class="workspace-task-row" data-task-id="${esc(t.id||'')}"><span>${t.status==='completed'?'✓':t.status==='failed'?'⛔':'◌'}</span><span><b>${esc(t.title||t.prompt||'Tarea')}</b><small>${esc(t.status||'queued')} · ${esc(t.capability||'general')}</small></span></button>`).join('')||'<small>No hay tareas todavía.</small>'}</div>`;}
  function taskComposer(capability,label,current){open(`Crear con Bitey · ${label}`,'Describe el resultado que quieres. Bitey decidirá la ruta cognitiva y las herramientas necesarias.',`<form id="workspace-task-form" class="workspace-task-composer"><label for="workspace-task-prompt"><b>¿Qué quieres conseguir?</b></label><textarea id="workspace-task-prompt" rows="5" autofocus placeholder="Ej.: Analiza este tema, compara las opciones y prepara una recomendación..."></textarea><div class="workspace-composer-meta"><span>Espacio: ${esc(current?.name||'General')}</span><span>Planificación cognitiva antes de inferencia</span></div><button class="primary-action" type="submit">Ejecutar con Bitey</button></form>`);const form=document.getElementById('workspace-task-form');const input=document.getElementById('workspace-task-prompt');form?.addEventListener('submit',async e=>{e.preventDefault();const prompt=input?.value?.trim();if(!prompt)return;await executeFromWorkspace(capability,prompt,current);});setTimeout(()=>input?.focus(),0);}
  function workspaceComposer(){open('Nuevo espacio de trabajo','Crea un proyecto persistente para que Bitey pueda mantener contexto, tareas, memoria y resultados.',`<form id="workspace-create-form" class="workspace-task-composer"><label for="workspace-name"><b>Nombre del espacio</b></label><input id="workspace-name" required maxlength="80" placeholder="Ej.: Proyecto de negocio" style="width:100%;box-sizing:border-box;padding:12px;border:1px solid rgba(255,255,255,.12);border-radius:12px;background:rgba(255,255,255,.04);color:inherit;font:inherit"><label for="workspace-description"><b>Descripción</b></label><textarea id="workspace-description" rows="3" placeholder="¿Para qué utilizarás este espacio?"></textarea><button class="primary-action" type="submit">Crear espacio</button></form>`);document.getElementById('workspace-create-form')?.addEventListener('submit',async e=>{e.preventDefault();const name=document.getElementById('workspace-name')?.value.trim();const description=document.getElementById('workspace-description')?.value.trim();if(!name)return;const created=await createWorkspace(name,description);if(!created){document.getElementById('modal-text').textContent='No se pudo crear el espacio. Revisa la conexión con Bitey.';return;}setActive(created.id);open('Espacio creado','El nuevo espacio ya está activo.',`<div class="workspace-result"><div class="feature-row"><span>✓</span><span><b>${esc(created.name)}</b><small>${esc(created.description||'Contexto persistente listo')}</small></span></div><button class="primary-action" id="workspace-open-created" type="button">Abrir Workspace</button></div>`);document.getElementById('workspace-open-created')?.addEventListener('click',hub);});}
  async function executeFromWorkspace(capability,prompt,current){let w=current;if(w)setActive(w.id);if(!w){const ws=await workspaces();w=pickWorkspace(ws);if(w)setActive(w.id);}if(!w)w=await createWorkspace('Espacio general','Espacio persistente para trabajo general de Bitey IA');if(!w){open('Workspace de Bitey IA','No se pudo preparar el espacio de trabajo.');return;}setActive(w.id);const plan=await inspectCognitive(prompt,capability,{workspace:true,workspace_id:w.id});if(!plan){open('Workspace de Bitey IA','Bitey no pudo obtener el contrato cognitivo. La tarea no se ejecutó.');return;}const live=document.createElement('div');live.innerHTML=window.BiteyLiveWorkspace?.progress(plan,'planning')||phaseMarkup(plan,'planning');open('Bitey está pensando…',`Espacio activo: ${w.name}. La ejecución queda bajo control del cerebro cognitivo.`,live.innerHTML);window.BiteyLiveWorkspace?.start(body());const task=await createTask(w.id,capability,prompt);if(!task){window.BiteyLiveWorkspace?.stop();open('Workspace de Bitey IA','No se pudo crear la tarea.');return;}const executed=await runTask(w.id,task.id);window.BiteyLiveWorkspace?.stop();if(!executed){open('Workspace de Bitey IA','La tarea quedó creada pero no pudo iniciarse.');return;}executed.cognitive_plan=plan;open('Resultado de Bitey IA',`Espacio: ${w.name} · tarea ${executed.status||'finalizada'}.`,detailMarkup(executed));}
  async function hub(){const[c,ws]=await Promise.all([catalog(),workspaces()]);const current=pickWorkspace(ws);if(current)setActive(current.id);const caps=c?.capabilities||[{id:'chat',label:'Chat',kind:'conversation'},{id:'deep_research',label:'Investigación profunda',kind:'research'},{id:'documents',label:'Documentos',kind:'artifact'},{id:'slides',label:'Presentaciones',kind:'artifact'},{id:'spreadsheets',label:'Hojas de cálculo',kind:'artifact'},{id:'code',label:'Código',kind:'artifact'},{id:'files',label:'Archivos',kind:'context'},{id:'agents',label:'Agentes',kind:'orchestration'}];open('Workspace de Bitey IA','Tu centro de trabajo: planifica, ejecuta, revisa y reúne los resultados de Bitey.',`<div class="workspace-grid">${caps.map(x=>`<button class="workspace-card" data-cap="${esc(x.id)}"><span class="workspace-icon">${x.id==='deep_research'?'✦':x.id==='documents'?'▤':x.id==='slides'?'▥':x.id==='spreadsheets'?'▦':x.id==='code'?'⌘':x.id==='files'?'▣':x.id==='agents'?'◈':'◌'}</span><b>${esc(x.label)}</b><small>${esc(x.kind)}</small></button>`).join('')}</div><div class="workspace-list"><div class="feature-row"><span>◇</span><span><b>${esc(current?.name||'Espacio general')}</b><small>${ws.length?`${ws.length} espacios disponibles · espacio activo persistente`:'Crea tu primer espacio de trabajo'}</small></span></div><button class="primary-action" id="new-workspace">＋ Nuevo espacio</button>${current?taskHistoryMarkup(await recentTasks(current.id)):''}</div>`);body()?.querySelectorAll('[data-cap]').forEach(b=>b.onclick=()=>{const capability=b.dataset.cap;const label=b.querySelector('b')?.textContent||'capacidad';taskComposer(capability,label,current);});document.getElementById('new-workspace')?.addEventListener('click',workspaceComposer);body()?.querySelectorAll('[data-task-id]').forEach(b=>b.onclick=async()=>{const task=await (async()=>{try{const r=await fetch(`${API()}/workspaces/${encodeURIComponent(current.id)}/tasks/${encodeURIComponent(b.dataset.taskId)}`);return r.ok?r.json():null;}catch{return null;}})();if(task)open('Detalle de tarea de Bitey IA',`Estado: ${task.status||'queued'} · Espacio: ${current.name||''}`,detailMarkup(task));});}
  window.BiteyWorkspace={hub,catalog,workspaces,getWorkspace,inspectCognitive,createTask,runTask,recentTasks,getActiveWorkspaceId:activeId,setActiveWorkspaceId:setActive};window.BiteyUI=window.BiteyUI||{};window.BiteyUI.workspace=hub;document.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('[data-workspace]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();hub();})));window.addEventListener('bitey:workspace-changed',()=>{});
})();
