(()=>{
const A=()=>`${window.BITEY_API_BASE||''}/api/v1`,B=()=>document.getElementById('modal-body'),M=()=>document.getElementById('modal-backdrop'),E=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const O=(t,x,h='')=>{const m=M();if(!m)return;document.getElementById('modal-title').textContent=t;document.getElementById('modal-text').textContent=x;B().innerHTML=h;m.classList.add('open')};
async function G(p,o){try{const r=await fetch(A()+p,o);return r.ok?await r.json():null}catch{return null}}
const catalog=()=>G('/workspace/catalog'),workspaces=async()=>((await G('/workspaces'))?.workspaces||[]),createWorkspace=n=>G('/workspaces',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:n})}),inspectCognitive=(p,c,x={})=>G('/workspace/cognitive/inspect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:p,capability:c,context:x})}),createTask=(id,c,p,m={})=>G(`/workspaces/${encodeURIComponent(id)}/tasks`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:p.slice(0,80)||'Nueva tarea',prompt:p,capability:c,metadata:m})}),runTask=(id,t)=>G(`/workspaces/${encodeURIComponent(id)}/tasks/${encodeURIComponent(t)}/run`,{method:'POST'}),recentTasks=async id=>((await G(`/workspaces/${encodeURIComponent(id)}/tasks`))?.tasks||[]);
const phase=p=>`<div class="workspace-cognitive-status"><b>Cerebro cognitivo de Bitey</b><small>${E(p?.route||'workspace')} · Pensando → Planificando → Investigando → Generando → Evaluando → Listo</small></div>`;
function artifacts(t){if(Array.isArray(t?.result?.artifacts)&&t.result.artifacts.length)return t.result.artifacts;if(Array.isArray(t?.result?.deliverables))return t.result.deliverables.map(x=>x.result?.artifact).filter(Boolean);return t?.result?.artifact?[t.result.artifact]:[]}
function artifactResult(t){const list=artifacts(t);const cards=list.map((a,i)=>`<article class="artifact-card"><div class="artifact-card-head"><span class="artifact-type">${E(a.artifact_type||'artifact')}</span><span class="artifact-status">${E(a.status||'ready')}</span></div><h4>${E(a.name||'Artefacto '+(i+1))}</h4><p class="artifact-format">${E(a.content?.format||a.format||'Bitey artifact')}</p><details><summary>Vista previa</summary><pre class="artifact-preview">${E(a.content?.content||a.content||'')}</pre></details></article>`).join('');return `<div class="workspace-result">${phase(t.cognitive_plan)}<div class="feature-row"><span>✓</span><span><b>${list.length} artefacto${list.length===1?'':'s'} listo${list.length===1?'':'s'}</b><small>Evaluación y gate cognitivo completados</small></span></div><section class="workspace-artifact-collection"><div class="artifact-collection-head"><h3>Resultados de Bitey</h3><span>${list.length} salida${list.length===1?'':'s'}</span></div><div class="artifact-grid">${cards||'<small>No hay artefactos autorizados.</small>'}</div></section><details class="workspace-trace"><summary>Ver ejecución cognitiva</summary><pre class="workspace-evidence">${E(JSON.stringify(t.result?.execution_trace||[],null,2))}</pre></details></div>`}
function researchResult(t){const r=t?.result?.research||{};const steps=Array.isArray(r.steps)?r.steps:[];return `<div class="workspace-result">${phase(t.cognitive_plan)}<div class="feature-row"><span>✓</span><span><b>Investigación completada</b><small>${steps.length} pasos acotados</small></span></div><pre class="workspace-evidence">${E(String(r.evidence_context||'Bitey no recuperó evidencia utilizable.').slice(0,16000))}</pre></div>`}
async function execute(c,p,w){const plan=await inspectCognitive(p,c,{workspace:true,workspace_id:w?.id});if(!plan)return null;const t=await createTask(w.id,c,p);if(!t)return null;const r=await runTask(w.id,t.id);if(!r)return null;r.cognitive_plan=plan;return r}
async function executeAndOpen(c,p,w){const r=await execute(c,p,w);if(!r){O('Workspace de Bitey IA','No se pudo completar la ejecución cognitiva.');return null}if(['documents','slides','spreadsheets','code'].includes(c))O('Artefactos de Bitey IA','Bitey completó generación, evaluación y autorización.',artifactResult(r));else if(c==='deep_research'||c==='browser_research')O('Investigación de Bitey IA','Investigación acotada y verificable.',researchResult(r));else O('Resultado de Bitey IA','Bitey completó la tarea.',phase(r.cognitive_plan)+`<pre class="workspace-evidence">${E(r.result?.answer||r.answer||'')}</pre>`);return r}
async function hub(){const[c,w]=await Promise.all([catalog(),workspaces()]);const caps=c?.capabilities||[{id:'chat',label:'Chat'},{id:'deep_research',label:'Investigación profunda'},{id:'documents',label:'Documentos'},{id:'slides',label:'Presentaciones'},{id:'spreadsheets',label:'Hojas de cálculo'},{id:'code',label:'Código'},{id:'files',label:'Archivos'},{id:'agents',label:'Agentes'}];const cur=w[0]||await createWorkspace('Espacio general');O('Workspace de Bitey IA','Espacio integral para investigar, crear y ejecutar.',`<div class="workspace-grid">${caps.map(x=>`<button class="workspace-card" data-cap="${E(x.id)}"><span class="workspace-icon">◈</span><b>${E(x.label)}</b><small>${E(x.kind||'workspace')}</small></button>`).join('')}</div><div class="workspace-list"><div class="feature-row"><span>◇</span><span><b>${E(cur?.name||'Espacio general')}</b><small>${w.length} espacios disponibles</small></span></div><button class="primary-action" id="new-workspace">＋ Nuevo espacio</button><div class="workspace-history"><b>Actividad reciente</b>${(await recentTasks(cur?.id)).slice(0,8).map(t=>`<div class="workspace-task-row"><span>${E(t.status||'queued')}</span><span>${E(t.title||t.prompt||'Tarea')}</span></div>`).join('')||'<small>No hay tareas todavía.</small>'}</div></div>`);B()?.querySelectorAll('[data-cap]').forEach(b=>b.onclick=async()=>{const p=window.prompt(`¿Qué quieres hacer con ${b.textContent.trim()}?`);if(p?.trim())await executeAndOpen(b.dataset.cap,p,cur)});document.getElementById('new-workspace')?.addEventListener('click',async()=>{const n=window.prompt('Nombre del espacio');if(n?.trim()){await createWorkspace(n.trim());hub()}})}
window.BiteyWorkspace={hub,catalog,workspaces,inspectCognitive,createTask,runTask,recentTasks,execute};window.BiteyUI=window.BiteyUI||{};window.BiteyUI.workspace=hub;document.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('[data-workspace]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();hub()})));
})();
