(() => {
  'use strict';
  const API = () => `${window.BITEY_API_BASE || ''}/api/v1`;
  const state = { timer: null, started: 0 };
  const phases = ['Pensando','Planificando','Investigando','Generando','Evaluando','Listo'];
  const esc = v => String(v ?? '').replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const phaseIndex = p => ({planning:1,researching:2,generating:3,evaluating:4,completed:5,ready:5}[p] ?? 1);
  function progress(plan, phase='planning') {
    const active = phaseIndex(phase);
    return `<div class="live-cognitive"><div class="live-head"><span class="live-pulse"></span><div><b>Bitey está trabajando</b><small>${esc(plan?.route === 'research' ? 'Investigación acotada' : plan?.route === 'artifact' ? 'Creación de resultado' : 'Razonamiento y ejecución')}</small></div><span class="live-time" data-live-time>0,0 s</span></div><div class="live-phases">${phases.map((x,i)=>`<span class="${i<active?'done ':''}${i===active?'active':''}">${i<active?'✓ ':''}${x}</span>`).join('')}</div></div>`;
  }
  function start(el){if(!el)return;state.started=performance.now();clearInterval(state.timer);const tick=()=>{const node=el.querySelector('[data-live-time]');if(node)node.textContent=((performance.now()-state.started)/1000).toFixed(1).replace('.',',')+' s';};tick();state.timer=setInterval(tick,100);}
  function stop(){clearInterval(state.timer);state.timer=null;}
  async function inspect(prompt,capability='chat',context={}){try{const r=await fetch(`${API()}/workspace/cognitive/inspect`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({prompt,capability,context})});return r.ok?await r.json():null;}catch{return null;}}
  async function getWorkspace(id){try{const r=await fetch(`${API()}/workspaces/${encodeURIComponent(id)}`);return r.ok?await r.json():null;}catch{return null;}}
  async function getWorkspaces(){try{const r=await fetch(`${API()}/workspaces`);return r.ok?(await r.json()).workspaces||[]:[];}catch{return [];}}
  function ensureStyles(){if(document.getElementById('bitey-workspace-context-style'))return;const s=document.createElement('style');s.id='bitey-workspace-context-style';s.textContent='.workspace-context-select{display:grid;gap:8px;margin-bottom:14px}.workspace-context-select select{width:100%;padding:11px 12px;border:1px solid rgba(255,255,255,.12);border-radius:12px;background:rgba(255,255,255,.05);color:inherit;font:inherit}.workspace-context-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.workspace-context-grid section{display:grid;gap:8px;padding:14px;border:1px solid rgba(255,255,255,.08);border-radius:14px;background:rgba(255,255,255,.025)}.workspace-context-grid section>b{font-size:14px}.workspace-context-grid section>small{opacity:.65}.workspace-context-item{display:grid;gap:3px;padding:9px;border-radius:10px;background:rgba(255,255,255,.035)}.workspace-context-item strong{font-size:11px;text-transform:uppercase;letter-spacing:.04em;opacity:.65}.workspace-context-item span{font-size:12px;line-height:1.45;max-height:52px;overflow:hidden}.workspace-context-summary{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.workspace-context-summary span{padding:6px 9px;border-radius:999px;background:rgba(255,255,255,.06);font-size:11px}@media(max-width:640px){.workspace-context-grid{grid-template-columns:1fr}}';document.head.appendChild(s);}
  function contextMarkup(data){const w=data?.workspace||{};const memory=data?.memory||[];const artifacts=data?.artifacts||[];const tasks=data?.tasks||[];return `<div class="workspace-context-panel"><div class="feature-row"><span>◇</span><span><b>${esc(w.name||'Espacio de trabajo')}</b><small>${esc(w.description||'Contexto persistente de Bitey')}</small></span></div><div class="workspace-context-grid"><section><b>Memoria</b><small>${memory.length} elementos persistentes</small>${memory.slice(0,5).map(m=>`<div class="workspace-context-item"><strong>${esc(m.memory_type||'context')}</strong><span>${esc(m.content||'')}</span></div>`).join('')||'<small>No hay memoria registrada todavía.</small>'}</section><section><b>Resultados</b><small>${artifacts.length} artefactos persistidos</small>${artifacts.slice(0,5).map(a=>`<div class="workspace-context-item"><strong>${esc(a.artifact_type||'artefacto')}</strong><span>${esc(a.title||a.name||a.id||'Resultado')}</span></div>`).join('')||'<small>No hay artefactos todavía.</small>'}</section></div><div class="workspace-context-summary"><span>${tasks.length} tareas</span><span>${artifacts.length} resultados</span><span>${memory.length} recuerdos</span></div></div>`;}
  async function openContextPanel(){ensureStyles();const modal=document.getElementById('modal-backdrop'),body=document.getElementById('modal-body');if(!modal||!body)return;const ws=await getWorkspaces();const current=ws[0];document.getElementById('modal-title').textContent='Proyectos y contexto';document.getElementById('modal-text').textContent='Bitey conserva el contexto de cada espacio y recupera sus resultados persistentes.';body.innerHTML=`<div class="workspace-context-select"><label for="bitey-context-workspace"><b>Espacio activo</b></label><select id="bitey-context-workspace">${ws.map(w=>`<option value="${esc(w.id)}">${esc(w.name||'Sin nombre')}</option>`).join('')||'<option value="">Sin espacios</option>'}</select></div><div id="bitey-context-content">${current?contextMarkup(await getWorkspace(current.id)):'<small>Crea un espacio desde Workspace para comenzar.</small>'}</div>`;const select=document.getElementById('bitey-context-workspace');select?.addEventListener('change',async()=>{const data=await getWorkspace(select.value);document.getElementById('bitey-context-content').innerHTML=contextMarkup(data);});modal.classList.add('open');}
  window.BiteyLiveWorkspace={progress,start,stop,inspect,getWorkspace,getWorkspaces,openContextPanel};
  document.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('[data-panel="projects"]').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openContextPanel();},true)));
})();
